<?php
$this->headTitle('Datepicker');

$this->headScript()->appendFile($this->basepath('/js/jquery-ui.min.js', 'text/javascript')); 
$this->headLink()->appendStylesheet($this->basepath('/css/jquery-ui.min.css')); 
?>

<h1>Datepicker</h1>

<p>
    Click the edit box below to show the datepicker.
</p>

<input type="text" class="datepicker" title="Type here"/>

<script>      
    $(document).ready(function() {
        $("input.datepicker").datepicker({ dateFormat: 'yy-mm-dd' });     
    });
</script>