<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Hello World')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <div class="container">               
            <div class="row">
                <!-- Page header -->
                <div class="col-md-12">
                    <div class="app-caption">Hello World - ADMINISTRATIVO!</div>
                </div>                
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Navigation bar -->
                    <nav class="navbar navbar-expand-lg navbar-light bg-light"  role="navigation">
                        <div class="collapse navbar-collapse" id="navbarNavDropdown">
                            <ul class="navbar-nav">
                                <li class="nav-item active">
                                    <a class="nav-link" href="<?= $this->url('home') ?>">Home <span class="sr-only">(current)</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="<?= $this->url('download', ['action' => 'file'], ['force_canonical' => true, 
                                    'query'=>['name'=>'amostra.txt']]); ?>">Downloads</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="<?= $this->url('about') ?>">Sobre Nós</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="<?= $this->url('doc', ['page'=>'contents']); ?>">Conteúdos</a>
                                </li>

                                <li class="nav-item dropdown active">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                                        Static Menu
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="<?= $this->url('static', ['page'=>'help']); ?>">Help</a>
                                        <a class="dropdown-item" href="<?= $this->url('barcode'); ?>">Código de Barras</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="<?= $this->url('partial-demo') ?>">Partial Demo</a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <!-- Breadcrumbs -->
                    <ol class="breadcrumb">
                        <li class="active">Home</li>
                    </ol>       
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <!-- Page content placeholder -->
                    <?= $this->content; ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <hr>                
                    <p>&copy; 2005 - <?= date('Y') ?> MarcioTech. All rights reserved.</p>
                </div>
            </div>
        </div> <!-- /container -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
    </body>
</html>
