<h1>Thank You! Mr(s). <strong><?= $data['name'] ?></strong></h1>

<p>
  <div class="alert alert-success">
    We will respond to the E-mail address you have provided.
  </div>
</p>

<p>
  <div class="alert alert-primary">
    The data provided were<br><br>
    <b>Name: </b><?= $data['name'] ?><br>
    <b>E-mail address: </b><?= $data['email'] ?><br>
    <b>Number Phone: </b><?= $data['phone'] ?><br>
  </div>
</p>

       
       


